/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cr.view;

import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import com.cr.controller.FacturaController;
import com.cr.factory.AparatoFactory;
import com.cr.factory.FacturaFactory;
import com.cr.model.Aparato;
import com.cr.model.Equipo;
import com.cr.model.Factura;
import com.cr.model.FacturaEquipo;
import com.cr.model.FacturaIPod;
import com.cr.model.FacturaTV;
import com.cr.model.IPod;
import com.cr.model.Televisor;
import com.cr.view.Table.FacturaTable;

public class FacturaView extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = -585526124799044611L;
    private FacturaController controller;
    private FacturaTable TableModel;

    /**
     * Creates new form FacturaView
     */
    public FacturaView() {
        initComponents();
        controller = new FacturaController();
        tbFacturas.setModel(new DefaultTableModel(new Object[][] { { null, null, null, null, null } },
                new String[] { "Factura", "Descuento", "Aparato" }));
        setTableModel();
    }

    public void setTableModel() {
        TableModel = new FacturaTable(controller.Listar());
        tbFacturas.setModel(TableModel);
    }

    private void loadTable() {
        tbFacturas.setModel(TableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAparato = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFacturas = new javax.swing.JTable();
        txtPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtVoltaje = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCds = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        txtTamanio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero:");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Descuento:");

        jLabel3.setText("Aparato:");

        cbAparato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo", "IPod", "TV" }));
        cbAparato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAparatoItemStateChanged(evt);
            }
        });

        tbFacturas
                .setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][] { { null, null, null, null }, { null, null, null, null },
                                { null, null, null, null }, { null, null, null, null } },
                        new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        jScrollPane1.setViewportView(tbFacturas);

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio:");

        jLabel5.setText("Fecha:");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoltajeActionPerformed(evt);
            }
        });

        jLabel6.setText("Voltaje");

        jLabel7.setText("Capacidad");

        jLabel8.setText("Tamaño");

        jLabel9.setText("Cantidad CD:");

        txtCds.setEnabled(false);
        txtCds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCdsActionPerformed(evt);
            }
        });

        txtCapacidad.setEnabled(false);
        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });

        txtTamanio.setEnabled(false);
        txtTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addGroup(layout
                        .createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(44, 44, 44).addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(31, 31, 31)
                        .addGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPrecio)
                                        .addComponent(cbAparato, javax.swing.GroupLayout.Alignment.LEADING, 0, 92,
                                                Short.MAX_VALUE)
                                        .addComponent(txtDescuento, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtVoltaje))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(175, 175, 175).addComponent(jLabel5)
                                        .addGap(27, 27, 27).addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                134, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup().addGap(158, 158, 158)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel8).addComponent(jLabel9).addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCds).addComponent(txtCapacidad)
                                                .addComponent(txtTamanio))
                                        .addGap(37, 37, 37))))
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(
                                        jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardar)))
                                .addGap(37, 37, 37)))
                .addGap(86, 86, 86)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5).addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbAparato, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3).addComponent(jLabel9)
                        .addComponent(txtCds, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4).addComponent(jLabel7)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
                        .addComponent(txtVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8).addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26).addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNumeroActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtDescuentoActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPrecioActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFechaActionPerformed

    private void txtVoltajeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtVoltajeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtVoltajeActionPerformed

    private void txtCdsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCdsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCdsActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCapacidadActionPerformed

    private void txtTamanioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTamanioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTamanioActionPerformed

    private void cbAparatoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbAparatoItemStateChanged
        // TODO add your handling code here:
        if (evt.getSource() == cbAparato) {

            switch (cbAparato.getSelectedIndex()) {
            case 0:
                this.txtCds.setEnabled(true);
                this.txtCapacidad.setEnabled(false);
                this.txtTamanio.setEnabled(false);
                break;
            case 1:
                this.txtCds.setEnabled(false);
                this.txtCapacidad.setEnabled(true);
                this.txtTamanio.setEnabled(false);
                break;
            case 2:
                this.txtCds.setEnabled(false);
                this.txtCapacidad.setEnabled(false);
                this.txtTamanio.setEnabled(true);
                break;
            }
        }

    }// GEN-LAST:event_cbAparatoItemStateChanged

    private void limpiar(JTextField... txt) {

        for (JTextField t : txt) {
            t.setText("");
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {

        System.out.println("aqui");

        FacturaFactory factFactory = new FacturaFactory();
        AparatoFactory aparFactory = new AparatoFactory();
        Factura factura = factFactory.crearFactura(cbAparato.getSelectedIndex());
        Aparato aparato = aparFactory.crearAparato(cbAparato.getSelectedIndex());
        aparato.establecerVoltaje(Integer.parseInt(txtVoltaje.getText()));
        aparato.establecerPrecio(Double.parseDouble(txtPrecio.getText()));
        int numero = Integer.parseInt(txtNumero.getText());
        double descuento = Double.parseDouble(txtDescuento.getText());
        switch (cbAparato.getSelectedIndex()) {
        case 0:
            FacturaEquipo fact = (FacturaEquipo) factura;
            Equipo equipo = (Equipo) aparato;
            equipo.establecerCantidadCDs(Integer.parseInt(txtCds.getText()));
            fact.establecer(numero, equipo, descuento);
            controller.agregar(fact);
            break;
        case 1:
            FacturaIPod fact1 = (FacturaIPod) factura;
            IPod ipod = (IPod) aparato;
            ipod.establecerCapacidad(Double.parseDouble(txtCapacidad.getText()));
            fact1.establecer(numero, ipod, descuento);
            controller.agregar(fact1);
            break;
        case 2:
            FacturaTV fact2 = (FacturaTV) factura;
            Televisor tv = (Televisor) aparato;
            tv.establecerTamanio(Integer.parseInt(txtTamanio.getText()));
            fact2.establecer(numero, tv, descuento);
            controller.agregar(fact2);
            break;

        }
        setTableModel();
        limpiar(txtNumero,txtDescuento,txtPrecio,txtVoltaje,txtCapacidad,txtCds,txtTamanio);

        for (Factura it : controller.Listar()) {
            System.out.println(it);
        }
    }
    

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbAparato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFacturas;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCds;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamanio;
    private javax.swing.JTextField txtVoltaje;
    // End of variables declaration//GEN-END:variables
}
